# Generated by Django 5.2.7 on 2025-10-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('area', models.FloatField()),
                ('soilType', models.CharField(max_length=64)),
                ('waterResources', models.JSONField(default=list)),
                ('suitableFor', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
