# Generated by Django 5.2.7 on 2025-10-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('farmingType', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('landRequirement', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('contact', models.EmailField(max_length=254)),
            ],
        ),
    ]
