# Generated by Django 5.2.7 on 2025-11-04 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_land_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='accounts.user'),
            preserve_default=False,
        ),
    ]
