# Generated by Django 5.2.7 on 2025-11-04 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_land_created_at_land_priceperacre_land_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='land',
            name='suitableFor',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='land',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lands', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='land',
            name='waterResources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='land_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.land')),
            ],
        ),
    ]
