# Generated by Django 5.2.7 on 2025-11-05 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_land_status_alter_land_suitablefor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farming',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='farmings', to='accounts.user'),
            preserve_default=False,
        ),
    ]
