# Generated by Django 5.2.7 on 2025-11-05 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_farming_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='farming',
            name='concept',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farming',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmings', to='accounts.user'),
        ),
    ]
