# Generated by Django 5.2.7 on 2025-11-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_farming_concept_alter_farming_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farming',
            name='concept',
        ),
    ]
