# Generated by Django 5.2.7 on 2025-11-05 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_farming_concept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farming',
            name='user',
        ),
    ]
