# Generated by Django 5.2.7 on 2025-11-05 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_farming_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='farming',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='farmings', to='accounts.user'),
            preserve_default=False,
        ),
    ]
