# Generated by Django 5.2.7 on 2025-11-05 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_farming_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farming',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmings', to='accounts.user'),
        ),
    ]
