# Generated by Django 5.2.7 on 2025-11-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_landrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
