# Generated by Django 5.2.7 on 2025-11-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_farmer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
